//Number
Number.EPSILON
Number.MAX_SAFE_INTEGER
Number.MAX_VALUE
Number.MIN_SAFE_INTEGER
Number.MIN_VALUE
Number.NEGATIVE_INFINITY
Number.NaN
Number.POSITIVE_INFINITY
Number.isFinite
Number.isInteger
Number.isNaN
Number.isSafeInteger
Number.length
Number.apply
Number.call
Number.bind
Number.toString
Number.prototype
Number.parseInt
Number.parseFloat
Number.name
Number.caller
Number.prototype.toExponential
Number.prototype.toFixed
Number.prototype.toLocaleString
Number.prototype.toString
Number.prototype.valueOf
Number.prototype.toPrecision

